version: '3.8'

services:
  webapi:
    build:
      context: ..
      dockerfile: Barbershop.WebApi/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=database;Port=5432;Database=barbershop;Username=postgres;Password=postgres
    depends_on:
      - database

  database:
    image: postgres:15
    container_name: barbershop_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: barbershop
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: